targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          any_map: true
          checked: true
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true 