# -*- coding: utf-8 -*-
"""图表绘制模块"""

import pandas as pd
from typing import Dict, Type, Optional, List, Any

from app.core.logging import logger
from app.trading.renderers.base_chart_strategy import BaseChartStrategy
from app.trading.renderers.volume_wave_chart_strategy import VolumeWaveChartStrategy
from app.trading.renderers.volume_wave_enhanced_chart_strategy import VolumeWaveEnhancedChartStrategy
from app.trading.renderers.volatility_conservation_chart_strategy import VolatilityConservationChartStrategy

# 注册所有可用的图表策略（手动注册，保持向后兼容）
REGISTERED_CHART_STRATEGIES: Dict[str, Type[BaseChartStrategy]] = {
    VolumeWaveChartStrategy.STRATEGY_CODE: VolumeWaveChartStrategy,
    VolumeWaveEnhancedChartStrategy.STRATEGY_CODE: VolumeWaveEnhancedChartStrategy,
    'volatility_conservation': VolatilityConservationChartStrategy
}


def _generate_default_chart_strategy(strategy_code: str, strategy_class) -> Type[BaseChartStrategy]:
    """
    为策略生成默认的图表策略类
    
    适用于使用@register_strategy装饰器注册的策略，但没有专用图表策略类的情况
    
    Args:
        strategy_code: 策略代码
        strategy_class: 策略类
        
    Returns:
        动态生成的图表策略类
    """
    # 获取策略的图表配置
    chart_series = getattr(strategy_class, 'CHART_SERIES', {})
    strategy_name = getattr(strategy_class, 'STRATEGY_NAME', strategy_code)
    strategy_desc = getattr(strategy_class, 'STRATEGY_DESCRIPTION', '')
    
    class AutoGeneratedChartStrategy(BaseChartStrategy):
        """自动生成的图表策略类"""
        STRATEGY_CODE = strategy_code
        STRATEGY_NAME = strategy_name
        STRATEGY_DESCRIPTION = strategy_desc
        
        @classmethod
        def generate_chart_html(cls, stock_data: Dict[str, Any], **kwargs) -> str:
            """使用基类的通用渲染逻辑"""
            try:
                stock = stock_data['stock']
                df = stock_data['data']
                signals = stock_data.get('signals', [])
                theme = kwargs.get('theme', 'dark')
                
                chart_data = cls._prepare_chart_data(df)
                volume_data = cls._prepare_volume_data(chart_data)
                markers = cls._prepare_markers(df, signals)
                colors = cls.get_theme_colors(theme)
                
                # 准备额外的系列（基于CHART_SERIES配置）
                additional_series = ""
                if chart_series:
                    for series_id, series_config in chart_series.items():
                        series_type = series_config.get('type', 'line')
                        data_column = series_config.get('data_column', series_id)
                        
                        if series_type == 'line' and data_column in df.columns:
                            series_data = cls._prepare_ema_data(df, data_column)
                            color = series_config.get('color', '#888888')
                            additional_series += f"""
                            const {series_id}Series = chart.addLineSeries({{
                                color: '{color}',
                                lineWidth: 2,
                                title: '',
                                priceLineVisible: false,
                                lastValueVisible: false,
                            }});
                            {series_id}Series.setData({series_data});
                            """
                
                # 计算指标数据（通用指标）
                from app.trading.indicators.tradingview.volume_profile_pivot_anchored import calculate_volume_profile_pivot_anchored
                from app.trading.indicators.tradingview.pivot_order_blocks import calculate_pivot_order_blocks
                from app.trading.indicators.tradingview.divergence_detector import calculate_divergence_detector
                
                volume_profile = calculate_volume_profile_pivot_anchored(
                    df, pivot_length=20, profile_levels=25, value_area_percent=68.0, profile_width=0.30
                )
                
                pivot_order_blocks = calculate_pivot_order_blocks(
                    df, left=15, right=8, box_count=2, percentage_change=6.0, box_extend_to_end=True
                )
                pivot_order_blocks_for_pool = []
                if pivot_order_blocks:
                    for block in pivot_order_blocks:
                        pivot_order_blocks_for_pool.append({
                            'type': 'resistance' if block['type'] == 'resistance' else 'support',
                            'price_high': block['price_high'],
                            'price_low': block['price_low'],
                            'start_time': cls._get_time_string(df, block['start_index']),
                            'end_time': cls._get_time_string(df, block['end_index']),
                            'strength': block.get('strength', 0.8)
                        })
                
                divergence_data = calculate_divergence_detector(
                    df, pivot_period=5, max_pivot_points=10, max_bars=100,
                    check_macd=True, check_rsi=True, check_stoch=True, check_cci=True, check_momentum=True
                )
                
                # 准备EMA数据
                ema6_data = cls._prepare_ema_data(df, 'ema6') if 'ema6' in df.columns else []
                ema12_data = cls._prepare_ema_data(df, 'ema12') if 'ema12' in df.columns else []
                ema18_data = cls._prepare_ema_data(df, 'ema18') if 'ema18' in df.columns else []
                ema144_data = cls._prepare_ema_data(df, 'ema144') if 'ema144' in df.columns else []
                ema169_data = cls._prepare_ema_data(df, 'ema169') if 'ema169' in df.columns else []
                
                # 生成指标池脚本
                indicator_pool_scripts = cls._generate_indicator_pool_scripts(
                    ema6_data, ema12_data, ema18_data, ema144_data, ema169_data,
                    volume_profile, pivot_order_blocks_for_pool, divergence_data, None
                )
                
                additional_scripts = additional_series + indicator_pool_scripts
                
                return cls._generate_base_html_template(
                    stock=stock,
                    strategy_name=cls.STRATEGY_NAME,
                    strategy_desc=cls.STRATEGY_DESCRIPTION,
                    chart_data=chart_data,
                    markers=markers,
                    volume_data=volume_data,
                    additional_series="",
                    additional_scripts=additional_scripts,
                    colors=colors
                )
            except Exception as e:
                logger.error(f"生成自动图表失败: {str(e)}")
                import traceback
                logger.error(f"完整错误堆栈:\n{traceback.format_exc()}")
                raise
        
        @classmethod
        def _prepare_ema_data(cls, df, ema_column: str):
            """准备EMA数据"""
            if ema_column not in df.columns:
                return []
            data = []
            for idx, row in df.iterrows():
                time_val = cls._get_time_string(df, idx if isinstance(idx, int) else df.index.get_loc(idx))
                ema_val = row.get(ema_column)
                if time_val and ema_val is not None and not pd.isna(ema_val):
                    data.append({'time': time_val, 'value': float(ema_val)})
            return data
        
        @classmethod
        def _get_time_string(cls, df, idx: int) -> str:
            """获取时间字符串"""
            import pandas as pd
            if 'date' in df.columns:
                date_val = df.iloc[idx]['date']
                if isinstance(date_val, str):
                    return date_val[:10]
                elif isinstance(date_val, pd.Timestamp):
                    return date_val.strftime('%Y-%m-%d')
            return str(idx)
    
    return AutoGeneratedChartStrategy


def _auto_generate_chart_strategies():
    """
    为所有已注册的策略自动生成图表策略（如果尚未有专用图表策略）
    """
    # 延迟导入，避免循环依赖
    from app.trading.strategies import REGISTERED_STRATEGIES
    
    for strategy_code, strategy_class in REGISTERED_STRATEGIES.items():
        # 如果策略已有专用图表策略，跳过
        if strategy_code in REGISTERED_CHART_STRATEGIES:
            continue
        
        # 为策略生成默认图表策略
        chart_strategy_class = _generate_default_chart_strategy(strategy_code, strategy_class)
        REGISTERED_CHART_STRATEGIES[strategy_code] = chart_strategy_class
        logger.info(f"📊 已自动生成图表策略: {strategy_code} ({chart_strategy_class.STRATEGY_NAME})")


# 自动生成图表策略（手动注册的优先级更高）
_auto_generate_chart_strategies()


def get_chart_strategy_by_code(strategy_code: str) -> Optional[Type[BaseChartStrategy]]:
    """
    根据策略代码获取图表策略类
    
    Args:
        strategy_code: 策略唯一标识代码
        
    Returns:
        对应的图表策略类，如果不存在则返回None
    """
    return REGISTERED_CHART_STRATEGIES.get(strategy_code)

def get_all_chart_strategies() -> Dict[str, Dict[str, str]]:
    """
    获取所有注册的图表策略信息
    
    Returns:
        包含所有图表策略信息的字典，键为策略代码，值为包含名称和描述的字典
    """
    return {
        code: {
            "code": code,
            "name": strat.get_strategy_name(),
            "description": strat.get_strategy_description()
        }
        for code, strat in REGISTERED_CHART_STRATEGIES.items()
    }

def generate_chart_html(strategy_code: str, stock_data: Dict[str, Any], **kwargs) -> str:
    """
    使用指定策略生成图表HTML
    
    Args:
        strategy_code: 策略代码
        stock_data: 股票数据字典，包含stock、data、signals等信息
        **kwargs: 策略特定的参数
        
    Returns:
        生成的HTML字符串，如果策略不存在则返回空字符串
    """
    strategy_class = get_chart_strategy_by_code(strategy_code)
    
    if strategy_class:
        return strategy_class.generate_chart_html(stock_data, **kwargs)
    
    # 策略不存在，返回空字符串
    return "" 